@url = http://localhost:3000

### ADD A NOTE
POST {{url}}/api/add-note
content-type: application/json

{
	"app_pin": "123",
	"body": "this is the third local note",
	"rank": 3.6
}

### GET ALL NOTES
POST {{url}}/api/get-notes